---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: asdas
spec:
    type: googlecloudstorage
    parameters:
        - name: telemetry_types
          value:
            - Logs
        - name: bucket_name
          value: asdas
        - name: folder_name
          value: asd
        - name: project_id
          value: asd
        - name: auth_type
          value: auto
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: ""
        - name: bucket_location
          value: US
        - name: bucket_storage_class
          value: STANDARD
        - name: partition
          value: minute
        - name: compression
          value: none
        - name: object_prefix
          value: ""
        - name: timeout
          value: 30
        - name: drop_raw_copy
          value: true
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_storage_extension
          value:
            disabled: false
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: persistent_queue_fsync
                  value: true
                - name: timeout
                  value: 1
            type: file_storage_persistent_queue
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: asdasd
spec:
    type: bindplane_gateway
    parameters:
        - name: hostname
          value: 192.168.122.1
        - name: grpc_port
          value: 4317
        - name: http_port
          value: 4318
        - name: protocol
          value: grpc
        - name: http_path_prefix
          value: ""
        - name: headers
          value: {}
        - name: http_compression
          value: gzip
        - name: grpc_compression
          value: gzip
        - name: timeout
          value: 30
        - name: enable_tls
          value: false
        - name: insecure_skip_verify
          value: false
        - name: ca_file
          value: ""
        - name: tls_server_name_override
          value: ""
        - name: mutual_tls
          value: false
        - name: cert_file
          value: ""
        - name: key_file
          value: ""
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: drop_raw_copy
          value: true
        - name: persistent_queue_storage_extension
          value:
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: persistent_queue_fsync
                  value: false
                - name: timeout
                  value: 1
            type: file_storage_persistent_queue
        - name: enable_grpc_load_balancing
          value: false
        - name: grpc_load_balancing_policy
          value: round_robin
        - name: batch_enabled
          value: true
        - name: batch_send_batch_size
          value: 8192
        - name: batch_send_batch_max_size
          value: 0
        - name: batch_timeout
          value: 200ms
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: asdsad
spec:
    type: googlecloud
    parameters:
        - name: telemetry_types
          value:
            - Logs
        - name: project
          value: ""
        - name: auth_type
          value: auto
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: ""
        - name: timeout
          value: 5s
        - name: enable_compression
          value: true
        - name: enable_wal
          value: false
        - name: wal_max_backoff
          value: 60
        - name: default_location
          value: us-east1
        - name: drop_raw_copy
          value: true
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_storage_extension
          value:
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: persistent_queue_fsync
                  value: false
                - name: timeout
                  value: 1
            type: file_storage_persistent_queue
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: DevNull
spec:
    type: dev_null
    parameters:
        - name: telemetry_types
          value:
            - Logs
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: SecOpsLatamEnt-gRPC
spec:
    type: chronicle
    parameters:
        - name: protocol
          value: gRPC
        - name: region
          value: us
        - name: endpoint
          value: malachiteingestion-pa.googleapis.com
        - name: auth_type
          value: json
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: ""
        - name: log_type
          value: CATCH_ALL
        - name: customer_id
          value: 2f72e724-30a8-4f50-b370-eac94a33e320
        - name: project
          value: ""
        - name: forwarder
          value: ""
        - name: send_single_field
          value: true
        - name: raw_base
          value: Body
        - name: raw_attributes
          value: ""
        - name: raw_body
          value: ""
        - name: ingestion_labels
          value: {}
        - name: namespace
          value: ""
        - name: compression
          value: gzip
        - name: timeout
          value: 90
        - name: enable_batch_limit
          value: false
        - name: batch_request_size_limit
          value: 4e+06
        - name: log_errored_payloads
          value: false
        - name: drop_raw_copy
          value: true
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 40
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_storage_extension
          value:
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: persistent_queue_fsync
                  value: false
                - name: timeout
                  value: 1
            type: file_storage_persistent_queue
        - name: https_endpoint
          value: chronicle.googleapis.com
        - name: override_endpoint
          value: false
        - name: api_version
          value: v1alpha
        - name: metrics_interval
          value: 5m
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: SecOpsLatamGaia-gRPC
spec:
    type: chronicle
    parameters:
        - name: protocol
          value: gRPC
        - name: region
          value: us
        - name: endpoint
          value: malachiteingestion-pa.googleapis.com
        - name: auth_type
          value: json
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: ""
        - name: log_type
          value: CATCH_ALL
        - name: customer_id
          value: 14017248-91b1-4217-9e51-8c3aa4cba640
        - name: project
          value: ""
        - name: forwarder
          value: ""
        - name: send_single_field
          value: true
        - name: raw_base
          value: Body
        - name: raw_attributes
          value: ""
        - name: raw_body
          value: ""
        - name: ingestion_labels
          value: {}
        - name: namespace
          value: ""
        - name: compression
          value: gzip
        - name: timeout
          value: 5
        - name: enable_batch_limit
          value: false
        - name: batch_log_count_limit
          value: 1000
        - name: batch_request_size_limit
          value: 1.048576e+06
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_storage_extension
          value:
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: persistent_queue_fsync
                  value: false
                - name: timeout
                  value: 1
            type: file_storage_persistent_queue
        - name: https_endpoint
          value: chronicle.googleapis.com
        - name: override_endpoint
          value: false
        - name: api_version
          value: v1alpha
        - name: log_errored_payloads
          value: false
        - name: drop_raw_copy
          value: true
        - name: metrics_interval
          value: 5m
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: SecOpsLatamGaia-HTTPS
spec:
    type: chronicle
    parameters:
        - name: protocol
          value: https
        - name: region
          value: us
        - name: endpoint
          value: malachiteingestion-pa.googleapis.com
        - name: auth_type
          value: json
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: /path/to/json
        - name: log_type
          value: CATCH_ALL
        - name: customer_id
          value: 14017248-91b1-4217-9e51-8c3aa4cba640
        - name: project
          value: "117670667466"
        - name: send_single_field
          value: true
        - name: raw_base
          value: Body
        - name: raw_attributes
          value: ""
        - name: raw_body
          value: ""
        - name: ingestion_labels
          value: {}
        - name: namespace
          value: ""
        - name: compression
          value: gzip
        - name: timeout
          value: 90
        - name: enable_batch_limit
          value: false
        - name: batch_request_size_limit
          value: 1.048576e+06
        - name: log_errored_payloads
          value: false
        - name: drop_raw_copy
          value: true
        - name: retry_on_failure_enabled
          value: true
        - name: retry_on_failure_initial_interval
          value: 5
        - name: retry_on_failure_max_interval
          value: 30
        - name: retry_on_failure_max_elapsed_time
          value: 300
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_storage_extension
          value:
            disabled: false
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: persistent_queue_fsync
                  value: false
                - name: timeout
                  value: 1
            type: file_storage_persistent_queue
        - name: https_endpoint
          value: chronicle.googleapis.com
        - name: override_endpoint
          value: false
        - name: api_version
          value: v1alpha
        - name: metrics_interval
          value: 5m
