---
apiVersion: bindplane.observiq.com/v1
kind: Fleet
metadata:
    name: us-east
    displayName: US East
    labels:
        agent-type: observiq-otel-collector
        platform: windows
spec:
    configuration: ""
    selector:
        matchLabels:
            fleet: us-east
