apiVersion: bindplane.observiq.com/v1
kind: Processor
metadata:
    name: Add-IngestionSource-Hostname
spec:
    type: copy_field
    parameters:
        - name: telemetry
          value:
            - Logs
        - name: condition
          value:
            ottl: (attributes["chronicle_ingestion_label"]["ingestion_source"] == nil)
            ui:
                operator: ""
                statements:
                    - key: '["chronicle_ingestion_label"]["ingestion_source"]'
                      match: attributes
                      operator: DoesNotExist
                      value: ""
        - name: from_base
          value: Resource
        - name: from_attributes
          value: ""
        - name: from_body
          value: ""
        - name: from_resource
          value: host.name
        - name: to_base
          value: Attributes
        - name: to_attributes
          value: '["chronicle_ingestion_label"]["ingestion_source"]'
        - name: to_body
          value: ""