name: Bindplane Update Remote Content

on:
  push:
    branches:
      - main
    paths:
      - 'bindplane_content/**'
  workflow_dispatch: 

# Required for writing back otel configs to the repo.
permissions:
  contents: write

# Prevents concurrent and potentially out of order
# resource updates.
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  bindplane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: observIQ/bindplane-op-action@main
        with:
          bindplane_remote_url: ${{ vars.BINDPLANE_REMOTE_URL }}
          bindplane_api_key: ${{ secrets.BINDPLANE_API_KEY }}
          target_branch: main
          destination_path: bindplane_content/destination.yaml
          source_path: bindplane_content/source.yaml
          processor_path: bindplane_content/processor.yaml
          configuration_path: bindplane_content/configuration.yaml
          enable_otel_config_write_back: true
          configuration_output_dir: bindplane_content/otel/
          configuration_output_branch: otel
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_auto_rollout: true
